channels:
- conda-forge
dependencies:
- python=3.10.2
- pip<=21.2.4
- pip:
  - mlflow<3,>=2.1
  - argparse==1.4.0
  - cloudpickle==2.2.1
  - psutil==5.9.4
  - scikit-learn==1.2.1
  - typing-extensions==4.4.0
name: mlflow-env
